packages:
  - common-packages/*
  - packages/*
  - storybook
  - react-components/*

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  "@types/react": 19.2.0
  "@types/react-dom": 19.2.0
  eslint: ^9.27.0
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
